### ISSUE TITLE
Can't get the demo running locally

### ISSUE THREAD

**Issue by rojozabe** [matt-way/jsBinarySchemaParser#1]
Hi, I tried to run the demo (index.html) locally but it's not loading the images. Also, I'm trying to integrate this project into one of mine and there are a bunch of require instructions inside the main js that I don't know how to modify them to achieve the code to work.

EDIT: I confused of project sorry. This issue is related to gifuct-js.

**Comment by matt-way** [comment]
Hi, hopefully I can help. If you can put an issue on the gifuct project that would be helpful. Also is there any more information you can provide? What do you mean by 'not loading the images'?
