### ISSUE TITLE
Release as npm package

### ISSUE THREAD

**Issue by Zireael** [matt-way/jsBinarySchemaParser#3]
Hi, would you consider releasing the Schema Parser as a [NPM](https://www.npmjs.com/) / [Yarn](https://yarnpkg.com/lang/en/) package?

Thanks in advance!

**Comment by matt-way** [comment]
Yes definitely. Just trying to find the time. I'm planning to update this and another lib soon.

**Comment by matt-way** [comment]
Might still need some more testing, but I've refactored the code, and released a newer version to npm.
